yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: 'pnp'
pnpMode: 'loose'
packageExtensions:
  debug@*:
    dependencies:
      supports-color: '*'
  vue-router@*:
    dependencies:
      '@vue/runtime-core': '*'
  pinia@*:
    dependencies:
      '@vue/runtime-core': '*'
  webpack-dev-server@*:
    dependencies:
      'webpack': '*'
  '@babel/plugin-syntax-jsx@*':
    dependencies:
      '@babel/core': '*'
  '@babel/helper-compilation-targets@*':
    dependencies:
      '@babel/core': '*'
  vue-loader@*:
    dependencies:
      '@vue/compiler-sfc': '*'
